name: Builder

on:
  push:
    branches:
      - master

env:
  CMAKE_VERSION: 3.25.2
  LLVM_VERSION: 15.0.6
  NDK_VERSION: r25b

jobs:
  linux_and_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: sh scripts/setup_linux_cross_compile.sh
      - name: compile linux
        run: |
          python3 scripts/platform_builder.py --platform=linux --arch=all --cmake_dir=$HOME/opt/cmake-$CMAKE_VERSION --llvm_dir=$HOME/opt/llvm-$LLVM_VERSION
          cp include/dobby.h build/linux
          tar -zcvf build/dobby-linux-all.tar.gz build/linux
      - name: compile android
        run: |
          python3 scripts/platform_builder.py --platform=android --arch=all --cmake_dir=$HOME/opt/cmake-$CMAKE_VERSION --llvm_dir=$HOME/opt/llvm-$LLVM_VERSION --android_ndk_dir=$HOME/opt/ndk-$NDK_VERSION
          cp include/dobby.h build/android
          tar -zcvf build/dobby-android-all.tar.gz build/android
      - uses: actions/upload-artifact@v4
        with:
          name: linux-android
          path: build/dobby-*.tar.gz

  macos_and_iphoneos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - run: sh scripts/setup_macos_cross_compile.sh
      - name: compile macos
        run: |
          python3 scripts/platform_builder.py --platform=macos --arch=all --cmake_dir=$HOME/opt/cmake-$CMAKE_VERSION/CMake.app/Contents
          cp include/dobby.h build/macos
          tar -zcvf build/dobby-macos-all.tar.gz build/macos
      - name: compile iphoneos
        run: |
          python3 scripts/platform_builder.py --platform=iphoneos --arch=all --cmake_dir=$HOME/opt/cmake-$CMAKE_VERSION/CMake.app/Contents
          cp include/dobby.h build/iphoneos
          tar -zcvf build/dobby-iphoneos-all.tar.gz build/iphoneos
      - uses: actions/upload-artifact@v4
        with:
          name: macos-iphoneos
          path: build/dobby-*.tar.gz

  release:
    needs: [linux_and_android, macos_and_iphoneos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: "*"
          path: release/
          merge-multiple: true
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          artifacts: "release/*"
          allowUpdates: true
          replacesArtifacts: true
